INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('VGZNAAKLCTSL', 'AKQUACZTLAVV');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('NENCMPPTNUZO', 'MKXLLSMBVWLI');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YLOEZBLUHKOC', 'EFYDKLRTENGM');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('RZMEPGKXNGES', 'QHBIFMOTVZPA');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('AFFKNUPCIMES', 'HFWWCUCPCIXL');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('FDOWUPHZBXSV', 'ADLSSLPZUQWL');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('NCTUHQPAPAED', 'YLGIGCHXQIHH');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('TSJYDPJFFSPD', 'EJSNLAMZTZHV');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YIVJHISQMYVU', 'GGTHEHKGHSHA');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('TYJOOXUMHTZI', 'IJVMKVMCUKUC');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('MURFXYTFXHZY', 'NYNXIWYOEXTH');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('PVSLSRMKFCMF', 'XBCQTCFILVTO');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('DMJEREXVXONI', 'LWBYBBKBVCWJ');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('VIRTRYTIXKGY', 'YHBKHVDAQJBH');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('SMXSUFLHVKAG', 'ZQUFBQQFIGKE');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('ZLKNLSJTSCWE', 'EZRMGEEBVOLF');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('RBMTSFHHBMAR', 'CHNNSSEBTUBS');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('GKTKVYCUIMXR', 'QTBOCOCPJUDJ');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('NXEHEMVNQDAO', 'IZZGSVQFAOJF');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('KJIRPSJDHLMB', 'ZKTOKANBEUUI');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('RGBCBNAAWLCE', 'WLVSILPLZEGO');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('WWTIWWMUGZDQ', 'GPYOVXTNGVMW');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('KIMBOWHKATMT', 'AUSQFNTJJBKA');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('BHPZCWYREEPE', 'YDJZFRSZSDQO');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('GYXEJWIVOIYZ', 'ZRVJKYNFXQYH');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('FGRIXKAYZBDJ', 'BRDTINCWMRND');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YOAPFGKPVVNZ', 'DLNCDLXPJPZK');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('HGGTEKQPVUNX', 'BDGFXSJJXDHQ');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('EKRXMZJTFEQC', 'IYFAYAHWAGOL');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('BTHVZBMRYPFL', 'FKGVDNZELPZE');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('BSBYYCVWGKHA', 'MMEIMZEIVEJW');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('RQYEQVAXYWWF', 'TKFTSSWIZMBZ');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('BQFXWQQIJMIT', 'UZQYTZAJFQOB');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('CXTNFUFDSLDG', 'DPAVUMIKVNLX');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('KVGMQTDOHDRB', 'WUBYGQEBUFTF');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('JGIUMCOWCCPT', 'IEPRUBZWLRUB');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('PRFDUDYOYNDK', 'NIJOJLEVBGML');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('JYOYOVJMWGZL', 'IEPBUBBFXJZV');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('JXNDQPJEWEWC', 'BBOLCIQIYOIU');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('GNJDKUVJKJNH', 'WMLDRFAXMUKU');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('CJGMEUJVQEOR', 'PABIRVZUENYW');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('KDYUDOSQBHLU', 'MPVXOVWOXBJL');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('NFXMJUNSIMOH', 'QOAHHTFHFSQM');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YGKMFMRYZZGS', 'HLTFTHHCREIT');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('OWAISWLXXHUH', 'YDGTDUQWKPXN');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('FDDFUDQHDWUT', 'YUTWLALCPETP');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('AAMZYHBYCFLG', 'XUVKRSHKVDUJ');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('RNLDRMPQXQUT', 'YORJUDTDANAT');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YPRCXEMAAPRV', 'VHIDKRMXGUJD');
INSERT INTO effet_secondaire(nom_effet_effet_secondaire, type_effet_effet_secondaire) VALUES ('YUMFDVAQWPLP', 'IEPSALEMUKFD');

INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('RSTRFHLRQXPG', 'RNJSNYNSIYLT');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('HDWBUMMWJHGY', 'DZPUIUCFSKMF');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('IGHEDLVTTURA', 'PXWFIXYMNQQU');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('EUSETYBTMKRE', 'EAKOBJDETWIZ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('MISSVEKOMQHL', 'RXLGPYMVXRVN');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('LBMQMRXQAGRZ', 'VEWAPFQWFXQT');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('UFPLTUIYPEHP', 'YCQGMKJGKCCD');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('VWUXEINUUSSZ', 'ENUEMVTNBEQQ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('VEACOZJDTEGO', 'XVWVGPBUACVF');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('ZACVOMHBQHUD', 'DWZEULILDBYS');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('OOAASBGWFXQV', 'NGTVQAVMANCZ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('HOTBHEUYXNYC', 'FNTGSNKCWUBA');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('JMSHRBLFQPGY', 'EGIMGQAFNFDP');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('BYXFBIVJITQH', 'KSDHIZNPCRQN');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('OQSZXNMREWZE', 'EFQDYHNUVZGD');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('CJSNCKMQWAPM', 'GKZOLLUSQRVL');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('WBWUEBNDCFDR', 'QEOZPYPIPFPQ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('XOLARMMRVDCA', 'ERQIWKSOHMKJ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('BSYVCXKITNZJ', 'ZZCOAINXIEGB');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('WEIHQYYFDNZX', 'QCUVGLMRUCFZ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('FPBRTJBASPGU', 'MATLJRLEFKFE');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('OYUBDRUZEVIU', 'PUJQJNVNZWGF');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('FXORWQQSJQNA', 'CUATKLXWXGLL');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('WKXZYUAPZHTL', 'UTPHRLPERKPO');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('VTVCSZRBARJV', 'GVLNKFTNUTLO');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('WFLVLSILGQBR', 'TPOVVEJQZUEB');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('OCAWBTDHPTWM', 'NTHPOYPQRVUI');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('MKIGMYUAOUXT', 'WHTKTVNQQQTT');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('CUJFLIQFKSVD', 'UKXJHNYFMTMK');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('MIRBWHOKBBNS', 'XVSGCJTAFXVW');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('HUSOMDAOFEHZ', 'NXJLPNLOJAID');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('JFMDJKOYOHQH', 'AYVDBLUFQXIT');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('HIMIRBYPAYNN', 'XLHQFUAIJVEA');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('SYUUQTAEDYTO', 'WWUAIKQBYFZL');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('TIYVAMUAOFHP', 'KZXDNMSRMMPB');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('VPPXPMGQHXYT', 'OZRBTFSRKHHY');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('UMHCVFAAWWDU', 'CSBONQSVWLWQ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('RCRAFQEWKTZK', 'UJBDOYSDZUSD');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('SDTISXYYVZBQ', 'LODADFWWXXYI');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('SLZDBLSWMLVM', 'ZNMCLDLVSQCZ');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('ARFCNKXANERQ', 'ZABMPLDQQQIE');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('IUBTWOTABGOD', 'BPBARWQOIKVB');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('BVZWTDCUOQMY', 'BPXGMVALWNTW');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('KCSGPGPWAFGL', 'BEJTURVYJRQU');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('XPZHIOSTASAJ', 'UCMEDFWMEUQT');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('VSBRPQZVWBWS', 'ACVAAYJOGAUL');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('FMFBIPXXGJAU', 'SEKQSDCRWXLN');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('BDWVZWJOOFFM', 'KMMUJKNWIWGC');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('WQAWFVURQKWJ', 'GVSNHUXFNEHM');
INSERT INTO pathologie (nom_pathologie_pathologie, type_pathologie_pathologie) VALUES ('AHQWXZVJYFAE', 'BGAPWKNUZCQL');

INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('DRAMAHUDTOZJ','SIXNUYHAZJAM');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('UGLAWNSPBLPM','DPSNJBWVNMBG');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('DBPEAHKIMCUH','AANIWANFVQBF');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('SXAHFNFCCFIT','FFTWTRIYSPGH');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('PLJDOVIFGJCK','KWBRDOZIOGMC');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('XYTQGMNDUYZO','JAZTNRRULBEG');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('UURULQEVAPYK','FQZNQSAAISSF');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('PYGSUNTKSZKS','BPLQCGTJNVHH');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('YYCGYOOZGABL','ALERXDVVFECS');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('SYPVNWPXBODH','YOJQKUUQCSCC');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('FEJYUCIXIXFB','JPEPAPCQTOKF');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('SBOHFLWTYTGO','RBGFCVUZJSZH');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('HDQADKQHOSZV','OIOMUDUNAELU');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('BIGOQFTFDEPQ','UDRAIQVUYFYT');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('TJYHTIGSGNZP','ZLYUBVOLBEAT');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('ROUVORVXIRDG','EDUJQRYDHBBQ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('EDHSLUYYYZFQ','KATCKPCMLQMM');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('PRFEQLODYIKC','AECDXANLNBYQ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('XPKAYMINOLAE','XADVRBUQOBUJ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('QJGKWDDRVOIG','TPGDBRNASHSF');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('CNRMMWSUUOSP','YSTYCDEJHXHP');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('ENTELKKFCPVW','FOSEKOPVKTVS');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('PZMCCHGUJDXR','EMVMHNFLKGAX');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('YDXUUVCFFSDN','SRZDXLUIXYPB');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('VBXMDEGREEIH','TJFUCENQZQFR');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('FJDDQKWIBCMD','OAPTNGWHKMBD');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('GSXGYMEULXMQ','UOBUSTXEVUGN');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('OXLFGWCIQMSW','MXPLFFPXZHWP');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('SCCUUBISBXBK','VAYKZFVBRZXQ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('OHWBLGDZXBJX','IOUGKTNHLFQZ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('RNAILKRLRSTB','QPDVCLITDHRM');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('EROEEYZRKIPE','IWFXSPSFDLJC');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('LCBKULCXFWQI','LQTUVJMLMDGK');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('YSMPHLQHLJFC','DPSGFQZTNGUK');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('JUNXEVKIJRPP','HPYDCBDKEFTN');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('WVUEIHIHYQOO','TTTZMBRVRGNO');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('DWSVFOQPIWBX','SDDGRTAIHNSO');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('PWMSCMAGHKRZ','ZHJPYNBZAGGY');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('XXEZTUQXPGWV','GIQQZLDIMHTH');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('VXNQFCLQZWIC','WLOCBLIHDSHJ');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('IZLFFVPTUTPS','BMAAYIWIFNHB');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('SWNDKAMOTIXY','TVNBWSQNGEAK');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('MWPFQZPOAIVC','VJYQGZWBXLKP');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('QFRRWTRVUKWL','CKZMYPYEDMHO');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('OYCKJHXPUKBB','VPKHRTWRYIWY');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('AXTXINCELLER','VKFEEVKXWTJA');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('AOBILJOCPHSY','BQFSRYNVJQAS');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('UXZJVVTAAWGQ','ESHFQZHMQOIP');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('NWYICTCEVWZX','PMIVZJPLYKTG');
INSERT INTO symptome(nom_symptome_symptome, type_symptome_symptome) VALUES ('MHLIWRLKEDNW','WDMWMMSUXGZT');

INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('YODLFPLPYECH', 'NJYCUUAWQTQP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('CRGUYDHLNOHX', 'GHSWGRBSZFWF');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('QJEEYLCUAHYP', 'EKESJXCYIDGB');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('EZRMNGDDBXHR', 'HKNOMHCXDRBO');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('XNJQUVVJMQWA', 'HLVFNXYUPMUK');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('IVEAQAWMJIHG', 'FPFRAECVNWQP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('SYFIZRHWRKWZ', 'LQBMPISDTPJA');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('SJCPLLUZQTIS', 'IWTWSQSOLLTM');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('ROJGXZTQIFAZ', 'EQURNUHPDLWF');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('OUKGGEACDKVM', 'IPWITZDHISNF');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('NGWRDESBQARK', 'ODGROLQOIDGA');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('ILKKCXAPSCAU', 'GAWETQLDJQAC');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('ZNYUZCYRSBXI', 'TFIOJAVVBEMA');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('LAMFGGADBFCC', 'VAGRTEZFYNIR');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('QBXLBMETGYTK', 'DYYARCPFRDQV');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('FGEVBIWGEROM', 'BFQSAZYXQCKA');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('MWZWIIQJHLNX', 'ROUIYEQHBWRV');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('QSEGBKUDEVMO', 'OLHSQPNICHGP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('SPNUFTMIRGIP', 'EKPUIXIHTJJF');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('VGDLDVLFFEKH', 'BHEBMQJBQMWN');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('KFBSYIQJVVKJ', 'BQXSPAMJQADK');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('YSKLJIAGPDSA', 'ZIAUAYWGEFOD');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('FPZVFIXQOHVE', 'OCIUNXXUWVWP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('VHUKKSANEPUM', 'ISTKBPTKVZQJ');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('BCXRLBQHSEZL', 'EWABIUYWORUQ');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('GZSNYOLIHPPB', 'BBYFUNTARRKD');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('TNSDXTMUUHFG', 'WNIOIGFOVSHC');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('BSKUNWXEFNPV', 'CGRIWSSMPIDT');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('YTIGXLXSXXXH', 'OMDEKBTTCFOH');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('ZONQNDAMGLGJ', 'PZPDUZEJYJTA');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('LFMBIFZGGELL', 'BTEJZQBJBQGM');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('KEKRRJVPWZPP', 'MKEDIHDPVTNQ');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('UAKYSDZZKBNK', 'ZKIWVPVASMFR');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('LOAJXLJXFSKD', 'UEEOHBOZPVNP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('NUQVSMVLOBEY', 'WTPLZKECNTKP');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('JBZQSLDRSMSI', 'FYNAUQIUODZH');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('BFLTPNTVYOTK', 'GIZTYDOMLEGL');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('RFPEAGKJMDKI', 'ELSNTSDDZGVM');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('JGPUKRNTSHVL', 'BYDEGNBUNETD');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('TGRXSXLYUQMK', 'EGKORSXIUNIF');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('RTISFWSUXWZZ', 'WDMJJFFEFNTE');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('MTDONSHIGQRR', 'EARYYGDIRNGG');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('QTZBZCBIJUIG', 'WAAEMJBRMHLV');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('BNSEHUJOVCLG', 'JEKXFQHGLZNH');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('IRDCPWROUQIM', 'GGHMKGZCOURG');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('JNSAYSNAEQQU', 'WYDDAFQAOIBU');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('YRVSAIFFMFKH', 'ZCHWOKEGGBYS');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('IXMOJYIGJOTN', 'BGRYEGMKSMMJ');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('KHHPDFOFUIVG', 'EDZVGPUCTQMW');
INSERT INTO traitement (nom_traitement_traitement, type_traitement_traitement) VALUES ('XDKKNJUSTKIF', 'YZLNPHYBVBYY');

INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('VJBZVBLIQJTX', 'TXJLIGJYNBPJ', 'NTWDORUKGFTX');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('XEBURFJQESWI', 'OQUZUWSQVNJT', 'TWZCJMAYSUXG');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('TRHAJOXQSKYF', 'FAMYEEWTHJHH', 'XDNYNOSQJWEG');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('PCMUZSQLGOBV', 'MUVBRQCEWHOU', 'PQYQVMTJJALQ');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('NAGVXTFGHWJI', 'OEWQAZAPKFFQ', 'RBAAURJBAUBN');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('IWTGEORNAYYT', 'IVUJRMRMVGWG', 'ZZMHYRPSETQV');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('OLZQOTZSLGMW', 'QVEILIVTWBJA', 'RSKGTIKXVQAX');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('UFKAWJZCTADI', 'EIUZXTUWULLP', 'AIDXNVUUZNVD');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('GBQZGGONHJBG', 'FYPBXUKCDKYA', 'ACMWYWBAAEWL');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('UXXLHRMAQTDD', 'RGHSUSDRCXUJ', 'IURUAOVKSYFK');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('NYFNVCNJEFHR', 'YYJNJQQBXXRB', 'WPNIYSENTASJ');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('NCZYIEKIYVVX', 'BRDDBGJLDKWT', 'QQTVCEGGIBRC');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('BFKUADIGYPIT', 'HKVHBBVDBFCV', 'IFRNIYJCUHEY');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('PSUOVEYVQHSL', 'VENSHJBMTDTC', 'OIZUIEKFNZML');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('EWQMXQMCBKRM', 'LKLWVSXOOJOD', 'NHGYYETJQTJZ');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('MROYHURCUWMQ', 'BSQWIBJFGTAX', 'CISQFXCBBGME');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('AWALYHSQFODR', 'TVMWKZNEHXCG', 'MFQDSIRJXMXP');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('EDOWKCWYPVMX', 'INUTWKSWIRGL', 'ZDAQHPWLWPGQ');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('ACVVANMPZSFN', 'TZKNEGKSWQXB', 'IKIAQBMNSWKG');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('GGNUGKXAGYFF', 'KXEJPNROVPCN', 'BMYMCRFARJSF');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('MOHUQEXKRWJH', 'RODDILHBBXDN', 'HPZUPAQNFTUJ');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('IEPSSOUQPFGI', 'VYAWJFBNAPBP', 'HRFCNOJOYRFE');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('MWFWCJLHPHAS', 'STBLTDRJIHVX', 'FHNBEIOPGCQI');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('TFBSYBAGRZRW', 'ZMCAIZGSBPXM', 'TGSPVZTTTIBX');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('JPPIVHDBISTI', 'RNZRYDYIUFCX', 'NMKEJNRRCEXK');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('VFEAQSWDIYVX', 'JEOCEHKLRXUH', 'LTDRHPUTFJFX');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('FWQMTFYXIBTQ', 'MFWPEAUWMUWC', 'WASTUHYHWYFO');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('QQNUYNWJYFRT', 'MWQPNZRVKMGY', 'QFOKOINYTHZP');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('OJVFNUBMUSPH', 'BQKFQOOWPQCG', 'IGJISTVQONSB');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('PHGGWQGNWRTF', 'GVYRNFVEYKXV', 'ANMECOXEGBHE');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('BBEKRRREPMOI', 'OUROZHIQRYKZ', 'PHLNRCBAEXHT');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('ANMQLVBODFTE', 'WZHIKOYWYSQP', 'XLDDEMRXSNXB');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('AOUOYSSDHNZO', 'OMUIKQPWLMSQ', 'JGEORBUMMAUA');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('ZLUKREHGRJMG', 'TQCQKZDGEWTK', 'CUJZUMOHXSMM');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('QVZCFDLXTLDH', 'ALTGFUPWNVTH', 'MEDKHNEXFOLG');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('LURCDXVBDLDD', 'OJSCUJQJFKBA', 'JUPQDWRZNTLA');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('EMJADQBETSQS', 'XSKJPJNXRBRC', 'CQQZFNXSEAKF');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('PMZWOAPGMUNU', 'TFQWSTXOXETB', 'QNCIQBUEICOX');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('XHZHNYEDTSUD', 'PTNOXFYLRXZA', 'XMGCZANRPSEB');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('JEEYFGAALTCG', 'MQOCKIQQUTYM', 'MDJFYFKCLGHV');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('RFQIAJLIJLUP', 'PJSELGDFSWOZ', 'ETXILMTQKEEN');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('XQULHIOWZIRP', 'LZQXMYHMBUKZ', 'DNFBOGWNJYVY');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('WUBRJLQEORCQ', 'BXWGPAZYFUHP', 'OKMXTCXWUTTT');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('JVAPKPXGJZHU', 'OLEAXOCLARDV', 'NMNIZFSAFSJD');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('VISRVCYRSQSI', 'ZGQQHPOCPYOW', 'MJNNYPOBGEKD');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('NBDIFJHLZMAO', 'SQHGYYHYDBWX', 'FGRXNTAKWXUC');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('WWFOMIGMNZVV', 'WKYRPLDWROTP', 'GDMRBTVZINIR');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('RHOGUMBCABOM', 'DPRUYPCUCGKY', 'CYHWDLGSGQOF');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('QSPUCPXYBIEL', 'EKZBHFZKCZIA', 'NKUGMCINTAYK');
INSERT INTO vaccin (nom_vaccin_vaccin, type_vaccin_vaccin, fabricant_vaccin) VALUES ('ROCTFPEHVCAH', 'WBHXDMUWITGN', 'ZANISXXWGCYB');

INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('STRPJABRBBAM' , 'KFJEYAPOVBFU', 8580);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('PYOXYLHVABUR' , 'AAXQVKTIHFZD', 14472);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('QWGEOOSCMVPK' , 'LAYFDKUMTKTE', 8157);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('BLSYXVFWVXYT' , 'HUJZZACIOAJA', 3479);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('NFWHOISOSGZT' , 'OMCYYOBKIAQK', 545);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HYXELWCDYOIO' , 'NYAUYNOZSKCY', 25984);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('XZIIXADOBELG' , 'CAQMMDUDUNBA', 4537);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('LBITRVKSTCRL' , 'FCTYXMSZXBOW', 7701);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('YVRCCZMOBZGP' , 'SUWQLLIRHROO', 15492);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('VQKBNPLJDUYU' , 'ZTZFKHOJYGUQ', 5276);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('JYEJHTLLPEEB' , 'YBSMIKJISWJU', 32365);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('IFSDGTXLNYCE' , 'KXDOFETAHEOU', 13137);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('MQHCZYTTPAPZ' , 'XFXHCFOHRWGC', 26525);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HCDBZWOZUEFS' , 'PAQSXJLUMXSP', 17362);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('QTPNTYRBJWLU' , 'NGHEUBXBRIEN', 21780);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('URQUWLFOIYPG' , 'WWLNKSGZIBVF', 11913);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('SRANMQVFPHAX' , 'BOMEWHRGCADI', 22638);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('TKUABXZAMUSF' , 'NKNZNDYFTEWO', 13806);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('CWHATQHISFVY' , 'ANDKXSOKHFRN', 22775);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('DLKJKYIXMTXS' , 'KXQJBASSYIVO', 19813);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('LIDRRQWCWRIX' , 'NBQSGNFEIIYC', 7012);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('ASFCUPYRNMOV' , 'LIGCVQSWFABE', 21134);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('ZLACYJITDVZU' , 'YWXSNDSODOEB', 8171);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('YVFBXVVBLAWS' , 'ODKQQLHUIVAB', 8268);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('NPBUEOMEZUYX' , 'ISZVDTMZGHNZ', 28649);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('IJQVJHBNCNIV' , 'NDNUDMQCJNND', 12123);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('UMVHJBKRZYBT' , 'XZVWKDEMSIYU', 22698);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('PLGCSFYLUQSY' , 'VUDBFNNPMUFI', 11236);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HYLCAQVEONDJ' , 'IJEXLKJVBQTH', 9299);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('FPSMATDVHCEB' , 'YDFQSRNOUAOR', 16035);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('RZXDEPNSGWPP' , 'BAQHUOIHCNAS', 983);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('KTMOHUGOHLKR' , 'PPTYMUPJXTFH', 688);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('NDEOHAEUOUKR' , 'IWDZEWRVVQFK', 18746);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('YRRSFJFZGRRV' , 'NAJHDPTGEJXX', 10299);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('EJIALEPMSSYL' , 'NRPBUJXPDNMR', 30862);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('VNPJRYHDHIRS' , 'ZQNUCXKIMHBT', 30385);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('YWLFGDNVFWEO' , 'NHLTPXDGPZVP', 21686);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HBYBCQADSOPA' , 'BUJQFLVRMBDK', 4757);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('EEILOUHKAFBQ' , 'ORQDEYVBAIXL', 31082);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HYGNJRGKZEQS' , 'MPOOZNAZYGSY', 850);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('RYFOAYEHWTVL' , 'NRCECFCKVACF', 4657);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('NATUQNAEZDNU' , 'ZRBLYUFUEKOP', 903);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('UHQCBQCOIGTS' , 'WQIUCHDBRPVS', 2673);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('EWSIENZEEHVJ' , 'NBFVHWUENZFQ', 19452);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('HTFFJOMDSRNM' , 'PQXDJGDDSPRK', 3332);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('QSSXJSKSUKIR' , 'DXSQMQGKBFBY', 26601);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('CNDCNSJDAIVM' , 'FGPHOGLLGMTC', 14065);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('ZTKYQKXJLBKE' , 'ZOAVZENLBMHZ', 114);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('PVDDSUEUBOAI' , 'DTTQHMKBNPHA', 4265);
INSERT INTO localisation(region_localisation, ville_localisation, departement_localisation) VALUES ('UEFZPXFUMVVH' , 'YLXQYPWPGNRM', 12553);

INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('CNHYVJMMGJIG', 15205, 26470);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('RURLUSUQHFDY', 24166, 8682);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('QDOGHQGWVFIG', 9719, 20250);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('TECSONJJNEKK', 9975, 3939);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('ELCUYALAERIH', 8825, 2981);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('BXAIBFVLJBDE', 15138, 19828);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('UUCMPYBLRHDI', 14898, 24217);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('CASEUKYAMNIN', 14781, 4447);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('NAEPGIHYNHWU', 2740, 17624);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('IRSTXHSECTES', 16800, 13936);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('FRGGNIJHPDKN', 20363, 26902);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('KZWQOQBUKIHI', 31240, 29297);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('AVOYYVGWQUCR', 20283, 16416);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('DLYBLRQVEXNR', 27625, 19497);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('OXUZTDVPJKCC', 16036, 1914);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('YOHSOKORTXUY', 13445, 17330);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('ELINZHXPDJLQ', 27470, 30256);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('GXOTXMSOWGST', 23017, 10475);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('IZZWVBBBXPUV', 7641, 196);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('ITKTZPATDYVD', 842, 8756);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('FAAHDYZIOBHX', 15855, 8835);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('JYYILVUOHOXZ', 1778, 24966);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('YPMJBLYGJXII', 17695, 7767);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('DZKGJQIFCDTG', 8335, 30210);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('QXPQCNKZJJGZ', 28580, 17455);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('KVIFMMTLPBUC', 28679, 28926);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('OYWIXMCPJXTQ', 2739, 13997);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('TGHOPPLBTFLJ', 22771, 24685);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('EBWDLATOCSRA', 23152, 13198);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('XWTFVIBMJYVQ', 26621, 11755);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('GDOEIDWQGQLX', 18878, 10741);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('SJUKIXJRIKKW', 1473, 8125);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('TLFVSAXFMPQD', 7519, 21096);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('CYCXUJZZFSUP', 13492, 25932);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('MWAJFCXUVGDS', 208, 5623);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('UDVTMEZOYFMM', 21626, 16242);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('XCTCRNIATAFY', 13797, 9143);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('XLMEIEZBFHWB', 1903, 32078);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('MMYQJIWRUGHE', 25905, 8443);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('DQGIXIEHOESJ', 12317, 10424);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('TEABVILWADBM', 27500, 21256);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('KQFMPVZGAUQF', 31198, 19638);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('QYXQGIQCXGWC', 26062, 3075);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('OOZKNWYDZEDE', 6570, 844);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('UDRPGIWHUXIN', 4595, 13951);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('NVDAOSPVRMSZ', 14335, 12375);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('NHOAVOQSHEZB', 18931, 28655);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('LNCDVQXETYLT', 29953, 22530);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('HHZPOBLPKRYM', 22477, 14573);
INSERT INTO hopital (nom_hopital, nombre_lits_hopital, nombre_lits_reanimation_hopital) VALUES ('PSFOJNGWREHO', 10251, 2803);

INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18786 , true,'SYOANBWMXGGQ' , '2021-10-25', '2019-08-26', 'RBVUMJPDIJGL');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (30679 , false,'WLVTTTBGFZRN' , '2021-08-06', '2021-12-21', 'KHXLGXESKEYD');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (22187 , true,'AQHUURJVEIDG' , '2021-01-11', '2021-02-18', 'BQNPEORAPDLX');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (17227 , false,'XEGCKJWKVEWI' , '2021-03-22', '2019-03-15', 'NTUKGOGLZQIW');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (8897 , true,'UTNOHXCTJHEK' , '2019-07-24', '2021-02-01', 'GYOQHBMMTLZY');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (1143 , false,'LMTAZQKTMBAW' , '2019-01-23', '2019-08-06', 'UJYLEIAUDHMR');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (20680 , false,'VBMCIRNYZWNK' , '2020-02-24', '2019-06-09', 'XZFVYVNFDTBQ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (22171 , true,'ZOYUXNHZBVWQ' , '2020-01-12', '2021-05-11', 'JBAZFSGZUJVL');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (29757 , true,'YEBZCRQGPFJU' , '2019-04-20', '2020-12-22', 'AAVSJMEQKSUZ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (28098 , true,'SHAUYMBTRRNW' , '2021-01-16', '2021-10-14', 'UXYNEWWWXSKV');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18627 , false,'SSIPUAHIERDG' , '2020-04-02', '2020-12-17', 'WTZPOQXRVDJI');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (32219 , false,'VNDFJFETHXYX' , '2021-02-03', '2020-01-02', 'BWTFQHRSAYXY');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18555 , true,'GUBJIGCOPIZO' , '2021-01-24', '2021-02-09', 'SNDNCIDBPDLA');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (5162 , true,'VZCHOHNZXJMG' , '2019-07-09', '2020-07-01', 'JZJLEPGPUKDE');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (29006 , false,'XXNCPXPWASKZ' , '2019-04-21', '2021-09-02', 'MEHDYJPWWPPC');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (16517 , false,'NEYVEORUUGFR' , '2021-12-10', '2020-10-14', 'GWMYNDZXJVSV');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (19532 , true,'OIIFDRWONHIJ' , '2021-08-22', '2020-03-06', 'RJOZBOKXBHYW');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (31699 , true,'LTCOKBWREAKP' , '2020-02-02', '2019-09-18', 'EMFXXPJTSYWR');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (19748 , true,'EADKETWCJWTC' , '2021-07-21', '2020-11-20', 'GXRHXSPHNZUN');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (12951 , true,'YSJSDZIAZHNL' , '2019-07-22', '2019-07-17', 'RSULEMUDPTHC');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (291 , true,'AXHDKXZPBXXP' , '2019-02-18', '2021-01-06', 'HGNCYWRKJVWZ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (10480 , false,'KHOSIHFFHCPC' , '2021-10-11', '2020-10-28', 'LLCOEFWIAQYK');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (6778 , true,'NGCJTHNWBHCE' , '2021-06-10', '2020-01-12', 'TXOGKAPNCIOV');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (15726 , true,'FESCJHYHYFSP' , '2020-03-03', '2020-01-28', 'KOIMUEMXYBLH');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (9613 , false,'FPLBKAREFCAH' , '2021-02-02', '2021-01-16', 'YGQZTZEOTHEQ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (1090 , false,'TSERGPRNUXGD' , '2020-06-10', '2021-10-08', 'XWYNZSRLCPIE');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (29673 , false,'FGUNCMIAJZPC' , '2021-04-11', '2019-06-08', 'WGCWRTVTYXQR');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (24887 , false,'FZITYWQFLOLS' , '2020-05-24', '2020-05-27', 'YNTCEZAXGZTC');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (11050 , false,'IEYKCBVOGZMC' , '2021-08-17', '2019-05-14', 'PDIDTXTHUQEP');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (4249 , false,'RYWTHSHHMANL' , '2019-02-22', '2021-12-13', 'USDTCMIDEQDH');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (13195 , true,'VCNDIKCFLMWK' , '2019-11-21', '2020-08-07', 'RGZNAXUQCWEO');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (21886 , true,'AEFHULKBFERJ' , '2020-03-29', '2019-12-01', 'KVIQAPEPZOIC');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (4196 , false,'VPNDYWVNDQSF' , '2019-10-12', '2021-01-13', 'OTTQNLCCTJEF');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (16865 , true,'ZQRBVRGPHRHE' , '2021-11-14', '2019-06-15', 'ARGAQYYXWWDG');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (8189 , false,'FVAJWALTWEAF' , '2021-05-19', '2019-12-08', 'QJCYIKWHZVKK');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (14672 , false,'YVFZABNSCVGM' , '2019-05-13', '2021-08-09', 'TCSBZKXRLKVW');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (31653 , true,'WIMGAQKBSEUV' , '2019-07-05', '2021-09-25', 'FTRZBPKMXRCI');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (10640 , false,'ZZUZMIMLIVDO' , '2020-02-13', '2020-12-24', 'IQTKSEKPXAIZ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18487 , false,'ZBGXKXZONBLT' , '2021-12-27', '2019-08-22', 'CKFYAQCOUIUY');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (1965 , false,'NPOUGYXUAETV' , '2020-03-02', '2020-10-01', 'GGXBZKKUFSCA');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (25880 , true,'RHNQAAWAVOYB' , '2019-08-27', '2019-03-26', 'FWRXZRQPXKHP');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (23729 , false,'LRYORMYCCXWO' , '2021-04-17', '2019-08-25', 'KWSAGPUDACTD');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (6053 , true,'IOXOYSVMAIFJ' , '2020-09-24', '2019-07-29', 'CDDBAGQNKTFX');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (28863 , true,'GBCNLGLWKFPJ' , '2020-12-02', '2019-11-24', 'ZJUWJYLPQBHQ');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (631 , false,'JDETOCDBGOIS' , '2020-03-23', '2019-04-29', 'ZBWWTDSLLGJW');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (6640 , false,'FZGWIDKQTXIP' , '2019-11-11', '2021-02-07', 'GOSCWRKVVHTD');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (3705 , true,'LSBQLTRDAGEN' , '2020-12-27', '2019-02-10', 'FURIHMBVOWSK');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (10302 , true,'OPEFWZEWCQML' , '2019-01-10', '2019-07-19', 'LTCBYPQJLTAU');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18638 , false,'FRZORWFAFMSM' , '2019-04-07', '2020-07-18', 'VCZXONVDXVNX');
INSERT INTO personne(age_personne, sexe_personne, identifiant_personne, date_vaccin_1_personne, date_vaccin_2_personne,  ethnie_personne) VALUES (18826 , true,'UXWKYSFOWLGB' , '2020-09-15', '2020-05-02', 'ZLWXJKFTOKVG');

INSERT INTO cas (etat_actuel_cas) VALUES ('OOGSQDKYQDGJ');
INSERT INTO cas (etat_actuel_cas) VALUES ('HLWDEREENNYP');
INSERT INTO cas (etat_actuel_cas) VALUES ('HNRMUXHSFXFR');
INSERT INTO cas (etat_actuel_cas) VALUES ('FMVGCXDDQYUE');
INSERT INTO cas (etat_actuel_cas) VALUES ('OVLIMNVKHHDV');
INSERT INTO cas (etat_actuel_cas) VALUES ('UVOKZWUDNJMY');
INSERT INTO cas (etat_actuel_cas) VALUES ('YRGSCAIYGMTZ');
INSERT INTO cas (etat_actuel_cas) VALUES ('VFLSRDOEMZAZ');
INSERT INTO cas (etat_actuel_cas) VALUES ('HIZYKWJVBCZB');
INSERT INTO cas (etat_actuel_cas) VALUES ('VUYAHPIBEHTR');
INSERT INTO cas (etat_actuel_cas) VALUES ('YGQIYAECHDIB');
INSERT INTO cas (etat_actuel_cas) VALUES ('NBNDDOXUDDRE');
INSERT INTO cas (etat_actuel_cas) VALUES ('JFVZTAWVJUHV');
INSERT INTO cas (etat_actuel_cas) VALUES ('AJDNWNNZCWLF');
INSERT INTO cas (etat_actuel_cas) VALUES ('ZFGFQCRJSNTQ');
INSERT INTO cas (etat_actuel_cas) VALUES ('TCETJIHMWPEL');
INSERT INTO cas (etat_actuel_cas) VALUES ('TAGSISLCCHNH');
INSERT INTO cas (etat_actuel_cas) VALUES ('MVTEBSXYKVKQ');
INSERT INTO cas (etat_actuel_cas) VALUES ('DPJERNEEMSCQ');
INSERT INTO cas (etat_actuel_cas) VALUES ('UXATYUPTXCOM');
INSERT INTO cas (etat_actuel_cas) VALUES ('LWXNXVOGBUTC');
INSERT INTO cas (etat_actuel_cas) VALUES ('RFWGVBKEVBPK');
INSERT INTO cas (etat_actuel_cas) VALUES ('WIKFDCBMNTDK');
INSERT INTO cas (etat_actuel_cas) VALUES ('HBMBKAOJURGY');
INSERT INTO cas (etat_actuel_cas) VALUES ('MEQWHVKVFAYV');
INSERT INTO cas (etat_actuel_cas) VALUES ('OVLDRJRCTCUN');
INSERT INTO cas (etat_actuel_cas) VALUES ('GWFDGPUVYLRD');
INSERT INTO cas (etat_actuel_cas) VALUES ('CSBNZEMYVJCD');
INSERT INTO cas (etat_actuel_cas) VALUES ('HROGSQZURGMR');
INSERT INTO cas (etat_actuel_cas) VALUES ('HWOLZOBLSSWF');
INSERT INTO cas (etat_actuel_cas) VALUES ('EMQHDNDSYDUO');
INSERT INTO cas (etat_actuel_cas) VALUES ('PJFCPCBMXXVH');
INSERT INTO cas (etat_actuel_cas) VALUES ('NTWVPNHMYEUY');
INSERT INTO cas (etat_actuel_cas) VALUES ('FBZHIXJVLDQT');
INSERT INTO cas (etat_actuel_cas) VALUES ('RFJMGQGVTWFN');
INSERT INTO cas (etat_actuel_cas) VALUES ('QNFCJIPVWSSS');
INSERT INTO cas (etat_actuel_cas) VALUES ('QCTLSDROHFVF');
INSERT INTO cas (etat_actuel_cas) VALUES ('CDMRIWEGDTGE');
INSERT INTO cas (etat_actuel_cas) VALUES ('OWDTUDZLPAZC');
INSERT INTO cas (etat_actuel_cas) VALUES ('NOKJDRHEPOHZ');
INSERT INTO cas (etat_actuel_cas) VALUES ('DDWHLJRJGAOP');
INSERT INTO cas (etat_actuel_cas) VALUES ('AEYDZLTWFZOV');
INSERT INTO cas (etat_actuel_cas) VALUES ('WGXRTHEZJXIF');
INSERT INTO cas (etat_actuel_cas) VALUES ('JSYNEKTXPHKW');
INSERT INTO cas (etat_actuel_cas) VALUES ('NPJJZVXFEKYD');
INSERT INTO cas (etat_actuel_cas) VALUES ('LLGZTWGSBQIU');
INSERT INTO cas (etat_actuel_cas) VALUES ('MXEXXUFIFDVB');
INSERT INTO cas (etat_actuel_cas) VALUES ('EZFQDLZTWHWF');
INSERT INTO cas (etat_actuel_cas) VALUES ('PSMGDZBFEOCT');
INSERT INTO cas (etat_actuel_cas) VALUES ('STDXPYNIXLXD');

INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-11-28', '2019-11-26', 'ZYWSJRBDQICT' , 'LGUQAXWEWZJT');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-05-22', '2020-02-05', 'EXGNGDZDZABR' , 'TGYZPLRUKNGF');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-02-29', '2021-10-23', 'GVCVXVXTOEDG' , 'OUYTIKTLJJYI');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-05-20', '2021-04-06', 'JDBHJRCVFKGO' , 'BRFUOMBCJMUG');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-02-13', '2021-12-19', 'BZNPULEQIGND' , 'BNVRMIZZVCIK');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-10-07', '2020-09-17', 'QUKZMDUYUCSA' , 'JWTJUJUMXKDD');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-08-29', '2019-07-23', 'MUTDHIDQLKPR' , 'FLGGEFFAXSAA');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-04-28', '2021-07-06', 'UTAUYDJFMFGY' , 'URTBISSNALBK');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-10-11', '2019-09-06', 'TTKKDRFJNFOY' , 'WKOBGNVCLMXD');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-03-03', '2021-04-26', 'RMAXWITHYNNO' , 'TWZALNHBYVOP');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-05-23', '2020-08-17', 'JVHGNULYSVKV' , 'OWDNZYVDAVRU');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-07-03', '2019-03-21', 'NPBRAYEMKGAM' , 'WTMDIYWPANEJ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-05-20', '2019-09-28', 'LEPRFVRKWRLO' , 'ITIFMRTHHMEZ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-10-15', '2019-01-13', 'OUSPYTXJJBNX' , 'PADOBPMRFFIP');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-12-08', '2020-11-27', 'UMQENMYTFXIV' , 'VSSPTTSPQBFJ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-02-06', '2021-04-23', 'ZVVHEHAQUHXK' , 'LKOCMTMPGUOT');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-11-15', '2019-12-03', 'AUJMLEJRSPYY' , 'QLGRBJBKAFGG');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-05-17', '2019-07-09', 'LHWKIBBTCXAS' , 'QPISEZBKCATM');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-04-11', '2019-12-09', 'PYWCJDJIZKRJ' , 'ZYKKTBNQQYCT');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-08-01', '2021-09-01', 'CCLVOMJBWAYK' , 'UFBMOZXYUTSD');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-09-15', '2020-11-02', 'EWJAJMOYNWXS' , 'AITRFJSMUPMJ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-03-11', '2019-10-15', 'RRBZZTXKMJSJ' , 'SQSGLDGZIPNM');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-10-08', '2021-07-01', 'MHBGRBKZURLG' , 'TDZPVRQDNYBJ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-08-30', '2020-08-03', 'QNPDRFNMPXFV' , 'FYTXGVSATQXV');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-08-16', '2020-04-16', 'QULOYIDOZPIZ' , 'NKTIVJDQMYKJ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-03-02', '2020-12-18', 'WFRLVTWCGCIA' , 'GRDOXEHVPFCI');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-04-25', '2020-05-01', 'CGTXRHCDJBTZ' , 'NSYAFQVZEXRZ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-11-10', '2019-08-02', 'OEXFKZTIZFEV' , 'BAAYHVJSWWTD');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-08-07', '2021-02-11', 'EUAJQUEGFGUD' , 'FCXLAMJZYHGX');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-03-06', '2021-04-26', 'CBYJZCCKZVCV' , 'EWUYTSACVTOH');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-02-24', '2019-12-14', 'XMTIRXOXPEXD' , 'OQIKQRDGMTWL');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-01-30', '2020-12-21', 'QUCEWIQJFLJR' , 'COAPWJNXPGKG');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-03-15', '2019-10-27', 'ICRRQCPCOHDS' , 'VGHSWERKUGOE');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-10-11', '2019-07-14', 'OVTXRQKGQKUI' , 'NORUJZJSZBYM');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-06-04', '2020-01-30', 'HWSYXMARDHBS' , 'HQCIRJSQMPAI');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-05-15', '2021-10-27', 'BOEFZAQQAGCB' , 'XZYTKJZFREFL');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-03-27', '2019-02-25', 'NIMNPIVBRSTR' , 'TJKKOTHQLRBO');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-08-26', '2019-03-14', 'SNIDHVQJFXML' , 'KELSJQNVBGVL');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-01-10', '2019-09-13', 'ZDTABLZKLHUK' , 'RCKYBWHKTPUV');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-05-18', '2019-06-05', 'OLYZFNNRRSXS' , 'UDXNZBFQCPSV');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-06-21', '2021-07-16', 'DIGAIIOLKCRV' , 'AXFKNJVMCVYK');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-05-05', '2020-10-12', 'WBLMOLQZCXTL' , 'JYOESUMCLKBD');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-02-12', '2020-01-04', 'SMOIRIBOUFXE' , 'IAZWRHTZPJYN');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-04-28', '2020-03-19', 'BHBSTAPWATYV' , 'CDSXFJZISKWB');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-03-02', '2021-04-18', 'GGFFUBFMERML' , 'ZTXVNZPHBZTZ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-06-29', '2020-03-14', 'RTYCEBUBNTOT' , 'SUVWKCAMBLIS');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-02-10', '2020-10-30', 'IATJQRWAIUNL' , 'LWSKUIMRQJNN');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2019-03-15', '2020-07-04', 'UAVNWSXCFYUX' , 'XWTPJRNZIZFQ');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2021-05-25', '2019-07-18', 'KAFYGHVOZCKK' , 'WSTNLJTKBLOF');
INSERT INTO historique_cas (date_detection_historique_cas, date_maj_historique_cas, etat_cas_historique_cas, souche_virus_historique_cas) VALUES ('2020-04-12', '2021-06-22', 'XLORQEHDNCPN' , 'HFGGOJTHCJCV');

INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (3, 44);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (9, 46);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (12, 44);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (13, 10);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (37, 22);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (28, 31);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (18, 22);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (32, 39);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (20, 10);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (28, 34);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (2, 15);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (21, 2);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (33, 24);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (49, 34);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (23, 35);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (23, 24);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (42, 33);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (42, 1);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (17, 44);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (23, 19);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (5, 41);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (8, 37);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (49, 15);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (27, 5);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (15, 33);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (3, 17);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (11, 49);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (40, 37);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (23, 7);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (13, 38);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (44, 28);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (36, 3);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (49, 4);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (39, 34);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (30, 31);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (22, 25);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (37, 10);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (29, 10);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (7, 34);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (3, 19);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (46, 44);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (20, 40);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (32, 6);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (13, 43);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (42, 5);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (27, 10);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (32, 35);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (24, 27);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (6, 6);
INSERT INTO est_diagnostique (id_symptome_symptome, id_cas_cas) VALUES (37, 45);



INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (24, 17);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (25, 24);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (32, 3);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (42, 38);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (41, 29);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (15, 15);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (32, 3);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (3, 40);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (41, 16);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (23, 18);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (47, 44);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (34, 35);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (13, 13);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (43, 33);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (38, 21);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (25, 27);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (33, 42);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (44, 28);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (39, 31);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (43, 48);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (26, 3);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (45, 49);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (15, 41);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (1, 31);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (38, 14);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (3, 24);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (44, 46);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (35, 30);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (33, 39);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (12, 19);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (9, 10);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (49, 20);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (5, 38);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (31, 40);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (8, 25);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (1, 10);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (22, 24);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (41, 44);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (49, 34);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (21, 21);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (12, 12);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (45, 24);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (18, 2);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (32, 37);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (8, 15);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (45, 1);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (20, 25);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (40, 17);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (3, 25);
INSERT INTO recoit_le_traitement (id_cas_cas, id_traitement_traitement) VALUES (44, 27);

